# This formula is auto-generated by the CI pipeline via gen_brew_formula.sh.
# To regenerate: trigger the homebrew-package workflow or run:
#   ./vendor/script-helpers/scripts/gen_brew_formula.sh \
#     --name vellum \
#     --desc "Rich Markdown viewer for the terminal" \
#     --homepage "https://github.com/nikolareljin/vellum" \
#     --tarball dist/vellum-<version>.tar.gz \
#     --url "https://github.com/nikolareljin/vellum/archive/refs/tags/<version>.tar.gz"

class Vellum < Formula
  desc "Rich Markdown viewer for the terminal"
  homepage "https://github.com/nikolareljin/vellum"
  # url and sha256 are filled in by gen_brew_formula.sh at release time
  url "https://github.com/nikolareljin/vellum/archive/refs/tags/0.5.0.tar.gz"
  sha256 "PLACEHOLDER_SHA256_UPDATED_BY_CI"
  version "0.5.0"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", "--root", prefix, "--path", "."
  end

  test do
    assert_match "vellum", shell_output("#{bin}/vellum --help")
  end
end
