name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
      - '[0-9]*.[0-9]*.[0-9]*-rc*'
      - '[0-9]*.[0-9]*.[0-9]*-RC*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  release:
    uses: nikolareljin/ci-helpers/.github/workflows/rust-release.yml@production
    with:
      bin_name: "vellum"
      linux_gnu_aliases: "deb,pacman,yum,redhat"
